package com.scanner.utils

enum class ReaderStatus {
    NONE, SERVICE_BOUND, INIT_FAILED, FINGERS_RELEASED, FINGERS_READ_SUCCESS, FINGERS_READ_FAILED,
    SESSION_CLOSED, SESSION_OPEN, FINGERS_DETECTED, TAP_CANCELLED,
}